name: CI/CD Workflow to deploy to Amazon EC2

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    if: ${{ github.event_name == 'neverrun' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip      
          python -m pip install pipx
          pipx install poetry==1.3.1
          poetry export -f requirements.txt --output requirements.txt --without-hashes --with test
          pip install -r requirements.txt

      - name: Run linting and type checking
        run: |
          source venv/bin/activate
          flake8 .
          safety check --bare -r requirements.txt
          mypy .

      - name: Run Tests
        run: |
          source venv/bin/activate
          cd src
          pytest

  deploy:
    name: Deploy
    needs: [ ci ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.HOST_ADDRESS }}
          username: ${{ vars.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: ${{ vars.HOST_SSH_PORT }}
          script: |
            cd ~/resola
            ./deploy
